from dataclasses import asdict, dataclass, field
from enum import StrEnum
from typing import Any


class TimelineEventType(StrEnum):
    """Types of forensic transmission, authentication, and analysis events."""

    EMAIL_DATE = "EMAIL_DATE"
    RECEIVED_HOP = "RECEIVED_HOP"
    MTA_RELAY = "MTA_RELAY"
    AUTHENTICATION = "AUTHENTICATION"
    INGESTION_STARTED = "INGESTION_STARTED"
    PARSING_COMPLETED = "PARSING_COMPLETED"
    THREAT_ASSESSMENT = "THREAT_ASSESSMENT"
    INTEL_ENRICHMENT = "INTEL_ENRICHMENT"
    GEO_ENRICHMENT = "GEO_ENRICHMENT"


class TimestampQuality(StrEnum):
    """Reliability and provenance indicator of an event timestamp."""

    EXACT = "EXACT"  # High-precision server/system timestamp
    HEADER_DECLARED = "HEADER_DECLARED"  # Declared in RFC email/Received headers (subject to skew)
    SERVER_INGESTION = "SERVER_INGESTION"  # Generated by internal ingestion/database clock
    DERIVED = "DERIVED"  # Inferred from adjacent transmission hops
    ESTIMATED = "ESTIMATED"  # Estimated from sequence when clock is skewed
    MISSING = "MISSING"  # No valid timestamp available in evidence


@dataclass
class TimelineEvent:
    """A discrete chronological forensic milestone in the email lifecycle."""

    event_id: str
    event_type: TimelineEventType
    title: str
    description: str
    source: str
    timestamp_iso: str | None = None
    timestamp_raw: str | None = None
    timestamp_quality: TimestampQuality = TimestampQuality.MISSING
    delay_from_previous_seconds: float | None = None
    details: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Converts timeline event to dictionary payload."""
        data = asdict(self)
        data["event_type"] = self.event_type.value
        data["timestamp_quality"] = self.timestamp_quality.value
        return data


@dataclass
class ForensicTimelineResult:
    """Complete structured chronological investigation timeline for a case."""

    case_id: str
    total_events: int
    earliest_timestamp: str | None
    latest_timestamp: str | None
    has_missing_timestamps: bool
    events: list[TimelineEvent] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        """Converts complete timeline result to serializable dictionary."""
        return {
            "case_id": self.case_id,
            "total_events": self.total_events,
            "earliest_timestamp": self.earliest_timestamp,
            "latest_timestamp": self.latest_timestamp,
            "has_missing_timestamps": self.has_missing_timestamps,
            "events": [event.to_dict() for event in self.events],
        }
