"""Add url intelligence records

Revision ID: 2e196e1bfe7f
Revises: 060876cbd8a0
Create Date: 2026-08-25 17:35:06.829215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e196e1bfe7f'
down_revision: Union[str, None] = '060876cbd8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_intelligence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('registrar', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nameservers', sa.JSON(), nullable=False),
    sa.Column('a_records', sa.JSON(), nullable=False),
    sa.Column('aaaa_records', sa.JSON(), nullable=False),
    sa.Column('mx_records', sa.JSON(), nullable=False),
    sa.Column('txt_records', sa.JSON(), nullable=False),
    sa.Column('spf_record', sa.String(length=1024), nullable=True),
    sa.Column('dmarc_record', sa.String(length=1024), nullable=True),
    sa.Column('reputation', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_intelligence_records_case_id'), 'domain_intelligence_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_domain_intelligence_records_domain'), 'domain_intelligence_records', ['domain'], unique=False)
    op.create_index(op.f('ix_domain_intelligence_records_id'), 'domain_intelligence_records', ['id'], unique=False)
    op.create_table('url_intelligence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('raw_url', sa.String(length=2048), nullable=False),
    sa.Column('scheme', sa.String(length=16), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('registrable_domain', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=True),
    sa.Column('query', sa.String(length=2048), nullable=True),
    sa.Column('fragment', sa.String(length=2048), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('is_raw_ip', sa.Boolean(), nullable=False),
    sa.Column('is_shortener', sa.Boolean(), nullable=False),
    sa.Column('has_excessive_subdomains', sa.Boolean(), nullable=False),
    sa.Column('has_suspicious_path', sa.Boolean(), nullable=False),
    sa.Column('has_credential_path', sa.Boolean(), nullable=False),
    sa.Column('is_punycode', sa.Boolean(), nullable=False),
    sa.Column('has_homoglyphs', sa.Boolean(), nullable=False),
    sa.Column('is_lookalike', sa.Boolean(), nullable=False),
    sa.Column('has_suspicious_query', sa.Boolean(), nullable=False),
    sa.Column('has_mismatch_text', sa.Boolean(), nullable=False),
    sa.Column('lookalike_target', sa.String(length=255), nullable=True),
    sa.Column('explanation', sa.String(length=1024), nullable=True),
    sa.Column('reputation', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('provider_status', sa.String(length=64), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_intelligence_records_case_id'), 'url_intelligence_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_url_intelligence_records_id'), 'url_intelligence_records', ['id'], unique=False)
    op.create_index(op.f('ix_url_intelligence_records_raw_url'), 'url_intelligence_records', ['raw_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_intelligence_records_raw_url'), table_name='url_intelligence_records')
    op.drop_index(op.f('ix_url_intelligence_records_id'), table_name='url_intelligence_records')
    op.drop_index(op.f('ix_url_intelligence_records_case_id'), table_name='url_intelligence_records')
    op.drop_table('url_intelligence_records')
    op.drop_index(op.f('ix_domain_intelligence_records_id'), table_name='domain_intelligence_records')
    op.drop_index(op.f('ix_domain_intelligence_records_domain'), table_name='domain_intelligence_records')
    op.drop_index(op.f('ix_domain_intelligence_records_case_id'), table_name='domain_intelligence_records')
    op.drop_table('domain_intelligence_records')
    # ### end Alembic commands ###
