"""add_investigation_conclusion

Revision ID: 6c06cdea636e
Revises: 8eaca56fb757
Create Date: 2026-08-26 16:48:39.036373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c06cdea636e'
down_revision: Union[str, None] = '8eaca56fb757'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigation_conclusions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('primary_findings', sa.JSON(), nullable=False),
    sa.Column('supporting_evidence', sa.JSON(), nullable=False),
    sa.Column('probable_infrastructure', sa.String(length=255), nullable=False),
    sa.Column('attribution_assessment', sa.String(length=255), nullable=False),
    sa.Column('limitations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_conclusions_case_id'), 'investigation_conclusions', ['case_id'], unique=True)
    op.create_index(op.f('ix_investigation_conclusions_id'), 'investigation_conclusions', ['id'], unique=False)
    op.drop_index(op.f('ix_dummy_entity_id'), table_name='dummy_entity')
    op.drop_table('dummy_entity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_entity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dummy_entity_id'), 'dummy_entity', ['id'], unique=False)
    op.drop_index(op.f('ix_investigation_conclusions_id'), table_name='investigation_conclusions')
    op.drop_index(op.f('ix_investigation_conclusions_case_id'), table_name='investigation_conclusions')
    op.drop_table('investigation_conclusions')
    # ### end Alembic commands ###
