"""Add ip intelligence records

Revision ID: 8246472a3e68
Revises: 0010_create_evidence_records_table
Create Date: 2026-08-25 14:40:47.313545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8246472a3e68'
down_revision: Union[str, None] = '0010_create_evidence_records_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_intelligence_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=True),
    sa.Column('isp', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('hosting_provider', sa.Boolean(), nullable=True),
    sa.Column('proxy_vpn_indicator', sa.Boolean(), nullable=True),
    sa.Column('tor_indicator', sa.Boolean(), nullable=True),
    sa.Column('reputation', sa.String(length=50), nullable=True),
    sa.Column('abuse_threat_score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_intelligence_records_case_id'), 'ip_intelligence_records', ['case_id'], unique=False)
    op.create_index(op.f('ix_ip_intelligence_records_id'), 'ip_intelligence_records', ['id'], unique=False)
    op.create_index(op.f('ix_ip_intelligence_records_ip_address'), 'ip_intelligence_records', ['ip_address'], unique=False)
    op.drop_index(op.f('ix_dummy_entity_id'), table_name='dummy_entity')
    op.drop_table('dummy_entity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dummy_entity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dummy_entity_id'), 'dummy_entity', ['id'], unique=False)
    op.drop_index(op.f('ix_ip_intelligence_records_ip_address'), table_name='ip_intelligence_records')
    op.drop_index(op.f('ix_ip_intelligence_records_id'), table_name='ip_intelligence_records')
    op.drop_index(op.f('ix_ip_intelligence_records_case_id'), table_name='ip_intelligence_records')
    op.drop_table('ip_intelligence_records')
    # ### end Alembic commands ###
