"""Add analysis status

Revision ID: 85c22e3de24c
Revises: 6c06cdea636e
Create Date: 2026-08-26 17:23:09.547661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85c22e3de24c'
down_revision: Union[str, None] = '6c06cdea636e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('analysis_status', sa.String(length=50), server_default='QUEUED', nullable=False))
    op.add_column('cases', sa.Column('analysis_step', sa.String(length=100), server_default='Pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'analysis_step')
    op.drop_column('cases', 'analysis_status')
    # ### end Alembic commands ###
