"""Add origin_analysis to HeaderForensics

Revision ID: 89e0efbc76a1
Revises: cf5d371deca7
Create Date: 2026-08-26 12:54:13.528249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e0efbc76a1'
down_revision: Union[str, None] = 'cf5d371deca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('header_forensics', sa.Column('origin_analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('header_forensics', 'origin_analysis')
    # ### end Alembic commands ###
