"""add_evidence_status_and_analysis_history

Revision ID: 8eaca56fb757
Revises: b336e19690e6
Create Date: 2026-08-26 14:45:20.701906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaca56fb757'
down_revision: Union[str, None] = 'b336e19690e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('detector_version', sa.String(length=50), nullable=True),
    sa.Column('intel_provider', sa.String(length=100), nullable=True),
    sa.Column('provider_lookup_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_case_id'), 'analysis_history', ['case_id'], unique=False)
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    op.add_column('evidence_records', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evidence_records', 'status')
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_case_id'), table_name='analysis_history')
    op.drop_table('analysis_history')
    # ### end Alembic commands ###
