"""Add redirect chain to url intelligence

Revision ID: cf5d371deca7
Revises: 2e196e1bfe7f
Create Date: 2026-08-25 17:53:33.766619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5d371deca7'
down_revision: Union[str, None] = '2e196e1bfe7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_intelligence_records', sa.Column('redirect_chain', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url_intelligence_records', 'redirect_chain')
    # ### end Alembic commands ###
